services:
  db:
    image: postgres:16
    container_name: millionaire_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MILLIONAIRE
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MILLIONAIRE"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: millionaire_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    command: ["/app"]


volumes:
  pgdata: