curl -X POST "http://localhost:8080/api/millionaires" \
     -H "Content-Type: application/json" \
     -d '{
           "lastName": "Page",
           "firstName": "Jan",
           "middleName": "Edward",
           "birthDate": "1973-03-26",
           "birthPlace": "Lansing, USA",
           "company": "Google",
           "netWorth": 105000000000,
           "industry": "Technology",
           "country": "USA",
           "pathToPhoto": "/uploads/photos/larry_page.jpg"
         }'
